### PR TITLE
Update esformatter-jsx version & fix config

### LINKED ISSUE #99: indentation issues on jsx
I'm just trying `standard-format` on `atom` and i noticed behaviours i didn't expected working with `jsx`.

having this source file : 

```javascript
export class Foo extends React.Component {
  render() {
    return (
      <div></div>
    )
  }
}
```

is formated with alignement on parentheses : 
 
```javascript
export class Foo extends React.Component {
  render() {
    return (
    <div></div> // <= notice here 
    )
  }
}
```

and playing with parameters : 

```javascript
    return (
      <div>
        <span
          foo={bar}
          bar={baz} />
      </div>
    )
```

each parameter is aligned to the root node

```javascript
    return (
    <div>
        <span
    foo={bar}
    bar={baz} />
      </div>
    )
```

### PR DESCRIPTION
**Pull request by dotcypress**
New version of esformatter-jsx have fixes related to async/await
[Related info](https://github.com/millermedeiros/esformatter/issues/412#issuecomment-187417342)

fixes #99

### CODE REVIEW

**Comment by Flet** [comment]
LGTM!

**Comment by bcomnes** [comment]
Great!  Looks good to me too!

**Comment by bcomnes** [comment]
Released as 2.2.2

**Comment by feross** [comment]
Nice work!

**Pull request merged**
