### PR TITLE
expand eol comment regex to cover multiline comments

### LINKED ISSUE #60: standard-format doesn't remove trailing semicolons if they're followed by a multiline comment
Similar to #55, but this also occurs w/ multiline comments (per standard-format v1.3.6)
This was fixed for single line comments by PR #57 but still happens for multiline `/* ... */` comments due to RegExps.

---

```sh
$ standard-format --version
1.3.6
```

### Steps to reproduce:
1. Create a new file, _foo.js_, w/ the following code:

    ```js
    var config = {
      consumer_key: consumer_key,
      access_token: access_token
    }; /* useful comment */
```
    (and presumably if the multiline comment actually spanned multiple lines)

2. Run the following Terminal command: `$ standard-format -w foo.js`, or the following code to format and lint the code using **standard**:
    ```sh
    $ standard --format foo.js
    standard: Use JavaScript Standard Style (https://github.com/feross/standard)
      /Users/pdehaan/dev/tmp/pocketapi-test/foo.js:12:2: Extra semicolon.
    $ standard --version # 3.7.0
```

### Actual results:
The semicolon isn't removed during auto-formatting.

### Expected results:
The semicolon is removed.

### PR DESCRIPTION
**Pull request by Flet**
Fixes #60

### CODE REVIEW

**Comment by Flet** [comment]
Travis, you're silly.

```bash
flet@lappy:~/code/standard-format$ nave use 0.12.2
Already installed: 0.12.2
using 0.12.2
flet@lappy:~/code/standard-format$ node -v
v0.12.2
flet@lappy:~/code/standard-format$ npm test
npm info it worked if it ends with ok
npm info using npm@2.7.4
npm info using node@v0.12.2
npm info pretest standard-format@1.3.6
npm info test standard-format@1.3.6

> standard-format@1.3.6 test /home/flet/code/standard-format
> standard && tape test/*.js | tap-spec


  comments formatting

    ✓ Expect space or tab after // in comment
    ✓ Expect good comments to be unchanged

  test.js ran through formatter

    ✓ no runner errors

  multiline collapse

    ✓ two empty lines should collapse to one
    ✓ ten empty lines should collapse to one
    ✓ Remove padding newlines after curly braces

  multiline noop

    ✓ single empty line should be unmodified
    ✓ Dont mess with function tabbing
    ✓ allow single line object arrays

  deal with shebang line

    ✓ Expect formatter to not explode with shebang
    ✓ Expect program to be still have shebang

  singleline noop expressions

    ✓ Noop on single line conditional assignment
    ✓ Noop on single line object assignment
    ✓ Dont add padding to object braces
    ✓ Noop on singleline arrays
    ✓ Noop on named functions correctly spaced
    ✓ Noop non-functions with function in the name

  singleline transforms

    ✓ Anonymous function spacing between keyword and arguments
    ✓ Anonymous function spacing between arguments and opening brace
    ✓ Named function spacing between keyword and arguments
    ✓ Named function spacing between arguments and opening brace
    ✓ Squash spaces around variable value
    ✓ Space after variable name
    ✓ Squash spaces around assignment operator
    ✓ Space after commas in function parameters
    ✓ Space after commas in array
    ✓ Remove semicolons
    ✓ Space after colon (key-spacing)
    ✓ No Space before colon (key-spacing)
    ✓ Space after if
    ✓ Remove uneeded trailing semicolons that are followed by a comment
    ✓ Remove uneeded trailing semicolons that are followed by a multiline comment
   
   
   
  total:     32
  passing:   32
  duration:  3.1s

  All tests pass!
npm info posttest standard-format@1.3.6
npm info ok 
```

**Comment by bcomnes** [comment]
Travis was acting so weird today.  Also I was getting passing results locally and failing on travis.

**Comment by bcomnes** [comment]
Added an actual multiline comment test as well.

**Comment by Flet** [comment]
Speel guud @bcomnes! :)

Thanks for adding that test too!

**Pull request merged**
