### PR TITLE
Remove blank lines before closing braces

### LINKED ISSUE #110: Block must not be padded by blank lines.
Trailing padding within a block still is not removed (despite #23)

```js
function test () {
  var a = 2
  console.log(a)

}

test()
```

Executing `standard --format test.js` outputs `test.js:5:2: Block must not be padded by blank lines.`
without changing anything to the file (standard 5.2.1)

### PR DESCRIPTION
**Pull request by kt3k**
Hello

This change removes unnecessary blank lines before closing braces.

I think this change is useful for people who always pad their blocks with blank lines. ([like this](https://github.com/kt3k/class-component/blob/master/class-component.js))

Thanks,

----
close #110

### CODE REVIEW

**Comment by bcomnes** [comment]
Cool thanks!  Ill take test this out asap.

**Comment by benhutchins** [comment]
Thanks for the contribution @kt3k - I just mistakenly implemented the same fix in #131 ; be sure to try and reference relevant issue numbers in your messages. Helps the community around whatever project you're contributing to stay informed.

This PR will fix maxogden/standard-format#110, ricardofbarros/semistandard-format#4

**Comment by kt3k** [comment]
@benhutchins sorry for that and thanks for referencing the issues. I added the mention for closing the issue in my description. Thanks!

**Comment by nisaacson** [comment]
+1 can this get merged in? Removing blank lines is often a big manual process when converting projects over to standard

**Pull request merged**
