### PR TITLE
Add support for spaces after ES6 Class method names

### PR DESCRIPTION
**Pull request by gigafied**

### CODE REVIEW

**Comment by gigafied** [comment]
Fixes #134, #126, #116

**Comment by bcomnes** [comment]
Awesome @gigafied !  Thank you for this. Merging asap.

**Comment by feross** [comment]
Nice!

@bcomnes - any reason to not just merge this right now? Tests seem to pass.

**Comment by bcomnes** [comment]
LGTM. Haven't hat a chance to do release work recently so I held off. By all means merge!  I might sneak some time in this afternoon.

**Comment by bcomnes** [comment]
Merging for now.  Will try to capture the other PRs and see how far I can get later this week.

**Pull request merged**
