### PR TITLE
Update JSX and Testing Deps and disabled JSX formatting.

### PR DESCRIPTION
**Pull request by bcomnes**
Our JSX noop failed after the update, so I told JSX to stop doing stuff to the JSX.  I dont use JSX, so anyone feel free to chime in.

esformatter-jsx ^1.3.0 -> ^2.0.11
tap-spec -> 4.1.0
tape -> 4.2.0

### CODE REVIEW

**Comment by feross** [comment]
@Flet want to do a release?

**Comment by feross** [comment]
@bcomnes You could do a release too

**Comment by bcomnes** [comment]
Yeah I'll release today, just a few more thing I wanted to poke at first.

**Comment by bcomnes** [comment]
Released as 1.6.6: https://github.com/maxogden/standard-format/commit/340a3fb4e34576dbb6c8f48c8196302a6be1b605

**Pull request merged**
