### PR TITLE
JSX support

### PR DESCRIPTION
**Pull request by 0x80**

### CODE REVIEW

**Comment by bcomnes** [comment]
:+1: Looks good to me.  Can I get another +1 ?

**Comment by jhollingworth** [comment]
:+1:

**Comment by feross** [comment]
LGTM!

Released as v1.6.0.

**Comment by feross** [comment]
Not sure why it doesn't show up as merged in this PR, but it's merged on `master`.

**Comment by bcomnes** [comment]
Thanks @feross !

**Pull request closed without merging**
