### PR TITLE
Remove whitespace from inside parentheses.

### LINKED ISSUE #119: Remove whitespace from inside parentheses
Whitespace from inside if statement conditional parens, expression-wrapping parens and function parameter list parens should be removed.

Input: `if ( true ) {}`
Expected: `if (true) {}`
Actual: `if ( true) {}`

Input: `var condition = ( x === y )`
Expect: `var condition = (x === y)`
Actual: `var condition = ( x === y)`

Input: `function doStuff ( x, y ) {}`
Expect: `function doStuff (x, y) {}`
Actual: `function doStuff ( x, y ) {}`

### PR DESCRIPTION
**Pull request by ppvg**
Removes whitespace from inside if statement conditional parens, expression-wrapping parens and function parameter list parens.

Fixes #119.

I figured doing was better than asking. :)

### CODE REVIEW

**Comment by Flet** [comment]
Thanks! 

Published to npm as 1.6.8! :package:

**Comment by Flet** [comment]
@maxogden could you add @ppvg as a collab too?

**Comment by bcomnes** [comment]
Much appreciated!

**Comment by feross** [comment]
@maxogden ping

**Pull request merged**
