### PR TITLE
Enabled more jsx formatting rules

### PR DESCRIPTION
**Pull request by bcomnes**
Improves JSX formatting a fair amount.  WIP.

### CODE REVIEW

**Comment by Flet** [comment]
@bcomnes is this ok to merge as is?

**Comment by bcomnes** [comment]
Its going to start formatting JSX if this is merged, but it's probably better behavior than what goes on now.  I've been super swamped at work the last two weeks 😓

**Comment by Flet** [comment]
I did notice some frumpy formatting happens currently which is why I asked :)

No worries, I have some JSX stuff I can validate this against next week.

**Comment by bcomnes** [comment]
I'm tempted to merge this as is.  I tested it out on the react tutoral repo.  Results wern't qute how I wanted, but they seem in line with standard and with https://github.com/royriojas/esformatter-jsx  

e.g. I would like to see something like:

```jsx
return (
      <div className="comment">
        <h2 className="commentAuthor">
          {this.props.author}
        </h2>
        <span dangerouslySetInnerHTML={this.rawMarkup()} />
      </div>
    )
```

but instead get 

```jsx
return (
<div className="comment">
   <h2 className="commentAuthor">{this.props.author}</h2>
   <span dangerouslySetInnerHTML={this.rawMarkup()} />
</div>
)
```

Any thoughts on the matter?

**Comment by feross** [comment]
If it's better than what's currently happening, let's merge it.

**Comment by bcomnes** [comment]
OK, I'll merge this later today if someone else doesn't beat me to it.

**Comment by 0x80** [comment]
@bcomnes was this merged?

In the current version that I'm usign the indentation of the first tag is off.
```jsx
 render() {
    return (
    <div>
        <h1>...</h1>
        <button onClick={foo}>...</button>
        <canvas ref='canvas'/>
      </div>
    )
  }

```

**Comment by bcomnes** [comment]
@0x80 no not yet.  I'm going to get this and the new formatter rules pulled in, do a release, then try to improve the es6 situation with the new rules this weekend.

**Comment by 0x80** [comment]
:+1: awesome

**Comment by bcomnes** [comment]
Actually, I'm going to do a release with the new rules first so I can do a minor release first.

**Pull request merged**
