### PR TITLE
Fixed No space before comma in keys in destructuring assignment

### PR DESCRIPTION
**Pull request by drewhamlett**

### CODE REVIEW

**Comment by drewhamlett** [comment]
fixes https://github.com/maxogden/standard-format/issues/89

**Comment by feross** [comment]
Thanks for the fix. In the future, you shouldn't change the package version in PRs. That's the job of the person who does the npm release. There might be multiple changes that go into one release.

**Comment by feross** [comment]
Released as 1.6.5.

**Comment by drewhamlett** [comment]
You're right sorry about that.  Thanks.

**Pull request closed without merging**
